package edu.elon.lights.gui;

import processing.core.PApplet;

import java.awt.Font;

import g4p_controls.*;

public class EduLightsPApplet extends PApplet {

	private static final long serialVersionUID = 1L;
	private GButton buttonTrig; 
	private GButton lightsButton; 
	private GButton configBtn; 
	private GLabel labelTitle; 
	private static final int BACKGROUND_COLOR = 255;
	private static final int BUTTON_WIDTH = 270;
	private static final int BUTTON_HEIGHT = 190;
	private static final int WINDOW_WIDTH = 1000;
	private static final int WINDOW_HEIGHT = 600;
	private int thirdOfSize;
	private Font buttonFont = new Font("Dialog", Font.BOLD, 30);
	
	public static final void main(final String[] args) {
		  final String sketch = Thread.currentThread()
		    .getStackTrace()[1].getClassName();
		  PApplet.main(append(args, sketch));
	}

	public void setup(){
		  size(WINDOW_WIDTH, WINDOW_HEIGHT, JAVA2D);  
		  createGUI(); 
	}

	public void draw(){
		  background(BACKGROUND_COLOR);	  

	}
	
	public void buttonTrigClick(GButton source, GEvent event) { //_CODE_:buttonTrig:292081:
		  println("buttonTrig - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:buttonTrig:292081:

	public void lightsClick(GButton source, GEvent event) { //_CODE_:lightsButton:930120:
	  println("lightsButton - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:lightsButton:930120:
	
	public void configClick(GButton source, GEvent event) { //_CODE_:configBtn:514201:
		  println("configBtn - GButton >> GEvent." + event + " @ " + millis());
	} //_CODE_:configBtn:514201:



	// Create all the GUI controls. 
	// autogenerated do not edit
	public void createGUI(){
		G4P.messagesEnabled(false);
		  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
		  G4P.setCursor(ARROW);
		  if(frame != null){
		    frame.setTitle("Sketch Window"); 
		  }
		  buttonTrig = new GButton(this, 50, 220, 270, 190);
		  
		  buttonTrig.setFont(buttonFont);
		  buttonTrig.setText("Trigger Response Setup");
	
		  buttonTrig.setTextBold();
		  buttonTrig.addEventHandler(this, "buttonTrigClick");
		  lightsButton = new GButton(this, 370, 220, 270, 190);
		  lightsButton.setFont(buttonFont);
		  lightsButton.setText("Lights Library");
		  lightsButton.setTextBold();
		  lightsButton.addEventHandler(this, "lightsClick");
		  configBtn = new GButton(this, 680, 220, 270, 190);
		  configBtn.setFont(buttonFont);
		  configBtn.setText("Bridge Configuration");
		  configBtn.setTextBold();
		  configBtn.addEventHandler(this, "configClick");
		  labelTitle = new GLabel(this, 430, 100, 180, 40);
		  labelTitle.setFont(buttonFont);
		  labelTitle.setText("EduLights");
		  labelTitle.setTextBold();
		  labelTitle.setOpaque(false);
	}


	
}
